name: DanWorldExport
main: me.danny.danworld.DanWorldExportPlugin
version: 1.0.0
author: Danny
description: Export a selection to a DanWorld file
api-version: 1.20
commands:
  savedanworld:
    usage: /<command>
    description: Export your WorldEdit selection to a DanWorld.
