name: DanWorldExport
main: me.danny.danworld.DanWorldExportPlugin
version: 1.0.0
author: Danny
description: Export a selection to a DanWorld file
api-version: 1.20
commands:
  danworld:
    aliases: ['dw']
    usage: /<command>
    description: Manage DanWorlds.
