#[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[allow(non_camel_case_types)]
pub enum DanBiome {
    BADLANDS,
    BAMBOO_JUNGLE,
    BASALT_DELTAS,
    BEACH,
    BIRCH_FOREST,
    CHERRY_GROVE,
    COLD_OCEAN,
    CRIMSON_FOREST,
    DARK_FOREST,
    DEEP_COLD_OCEAN,
    DEEP_DARK,
    DEEP_FROZEN_OCEAN,
    DEEP_LUKEWARM_OCEAN,
    DEEP_OCEAN,
    DESERT,
    DRIPSTONE_CAVES,
    END_BARRENS,
    END_HIGHLANDS,
    END_MIDLANDS,
    ERODED_BADLANDS,
    FLOWER_FOREST,
    FOREST,
    FROZEN_OCEAN,
    FROZEN_PEAKS,
    FROZEN_RIVER,
    GROVE,
    ICE_SPIKES,
    JAGGED_PEAKS,
    JUNGLE,
    LUKEWARM_OCEAN,
    LUSH_CAVES,
    MANGROVE_SWAMP,
    MEADOW,
    MUSHROOM_FIELDS,
    NETHER_WASTES,
    OCEAN,
    OLD_GROWTH_BIRCH_FOREST,
    OLD_GROWTH_PINE_TAIGA,
    OLD_GROWTH_SPRUCE_TAIGA,
    PLAINS,
    RIVER,
    SAVANNA,
    SAVANNA_PLATEAU,
    SMALL_END_ISLANDS,
    SNOWY_BEACH,
    SNOWY_PLAINS,
    SNOWY_SLOPES,
    SNOWY_TAIGA,
    SOUL_SAND_VALLEY,
    SPARSE_JUNGLE,
    STONY_PEAKS,
    STONY_SHORE,
    SUNFLOWER_PLAINS,
    SWAMP,
    TAIGA,
    THE_END,
    THE_VOID,
    WARM_OCEAN,
    WARPED_FOREST,
    WINDSWEPT_FOREST,
    WINDSWEPT_GRAVELLY_HILLS,
    WINDSWEPT_HILLS,
    WINDSWEPT_SAVANNA,
    WOODED_BADLANDS,
}

impl From<u8> for DanBiome {
    fn from(value: u8) -> Self {
        match value {
            0 => DanBiome::BADLANDS,
            1 => DanBiome::BAMBOO_JUNGLE,
            2 => DanBiome::BASALT_DELTAS,
            3 => DanBiome::BEACH,
            4 => DanBiome::BIRCH_FOREST,
            5 => DanBiome::CHERRY_GROVE,
            6 => DanBiome::COLD_OCEAN,
            7 => DanBiome::CRIMSON_FOREST,
            8 => DanBiome::DARK_FOREST,
            9 => DanBiome::DEEP_COLD_OCEAN,
            10 => DanBiome::DEEP_DARK,
            11 => DanBiome::DEEP_FROZEN_OCEAN,
            12 => DanBiome::DEEP_LUKEWARM_OCEAN,
            13 => DanBiome::DEEP_OCEAN,
            14 => DanBiome::DESERT,
            15 => DanBiome::DRIPSTONE_CAVES,
            16 => DanBiome::END_BARRENS,
            17 => DanBiome::END_HIGHLANDS,
            18 => DanBiome::END_MIDLANDS,
            19 => DanBiome::ERODED_BADLANDS,
            20 => DanBiome::FLOWER_FOREST,
            21 => DanBiome::FOREST,
            22 => DanBiome::FROZEN_OCEAN,
            23 => DanBiome::FROZEN_PEAKS,
            24 => DanBiome::FROZEN_RIVER,
            25 => DanBiome::GROVE,
            26 => DanBiome::ICE_SPIKES,
            27 => DanBiome::JAGGED_PEAKS,
            28 => DanBiome::JUNGLE,
            29 => DanBiome::LUKEWARM_OCEAN,
            30 => DanBiome::LUSH_CAVES,
            31 => DanBiome::MANGROVE_SWAMP,
            32 => DanBiome::MEADOW,
            33 => DanBiome::MUSHROOM_FIELDS,
            34 => DanBiome::NETHER_WASTES,
            35 => DanBiome::OCEAN,
            36 => DanBiome::OLD_GROWTH_BIRCH_FOREST,
            37 => DanBiome::OLD_GROWTH_PINE_TAIGA,
            38 => DanBiome::OLD_GROWTH_SPRUCE_TAIGA,
            39 => DanBiome::PLAINS,
            40 => DanBiome::RIVER,
            41 => DanBiome::SAVANNA,
            42 => DanBiome::SAVANNA_PLATEAU,
            43 => DanBiome::SMALL_END_ISLANDS,
            44 => DanBiome::SNOWY_BEACH,
            45 => DanBiome::SNOWY_PLAINS,
            46 => DanBiome::SNOWY_SLOPES,
            47 => DanBiome::SNOWY_TAIGA,
            48 => DanBiome::SOUL_SAND_VALLEY,
            49 => DanBiome::SPARSE_JUNGLE,
            50 => DanBiome::STONY_PEAKS,
            51 => DanBiome::STONY_SHORE,
            52 => DanBiome::SUNFLOWER_PLAINS,
            53 => DanBiome::SWAMP,
            54 => DanBiome::TAIGA,
            55 => DanBiome::THE_END,
            56 => DanBiome::THE_VOID,
            57 => DanBiome::WARM_OCEAN,
            58 => DanBiome::WARPED_FOREST,
            59 => DanBiome::WINDSWEPT_FOREST,
            60 => DanBiome::WINDSWEPT_GRAVELLY_HILLS,
            61 => DanBiome::WINDSWEPT_HILLS,
            62 => DanBiome::WINDSWEPT_SAVANNA,
            63 => DanBiome::WOODED_BADLANDS,
            _ => DanBiome::PLAINS,
        }
    }
}
